name = input("Название питательной среды:")
concentration = input("Концентрация агара(%):")
temperature = input("Температура стерилизации (°С):")
print(f"{name}")
print(f"{concentration}")
print(f"{temperature}")
print(f"Название питательной среды: {name}\n Концентрация агара: {concentration}\n Температура стерилизации: {temperature}\n")
f = open("recipe.txt.docx", "w", encoding="utf-8")
print("Результаты работы", file=f)
f.close()
print("Файл `recipe.txt` успешно сформирован!")