name_device = input("Название оборудования:")
device_number = input("Инвентарный номер:")
state_device = input("Состояние оборудования(исправен/нет):")
amount_device = input("Количество")
print(f"Название оборудования:\t\t\t{name_device}\n")
print(f"Инвентарный номер:\t\t\t{device_number}\n")
print(f"Состояние оборудования (исправен/нет):\t{state_device}\n")
print(f"Количество:\t\t\t\t{amount_device}\n")
